baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Erin Lynn Fox"
theme = "fox"

[params]
    description = ""
    keywords = ""
    quote = "Stop and smell the tiger lilies."

[permalinks]
    blog = "/:year/:month/:slug/"

[taxonomies]
